<a href="https://colab.research.google.com/github/Somesh140/NLP_sentiment_analysis/blob/main/Keras_sentiment_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Sentiment Analysis on IMDB dataset

In [9]:
from keras.datasets import imdb
from keras import Sequential
from keras.layers import Dense, SimpleRNN, Flatten

In [3]:
(X_train,y_train),(X_test,y_test)=imdb.load_data()

17464789/17464789 [==============================] - 1s 0us/step


In [4]:
X_train.shape

(25000,)

In [5]:
X_test.shape

(25000,)

In [6]:
y_train

array([1, 0, 0, ..., 0, 1, 0])

In [7]:
print(len(X_train[2]))
print(len(X_train[3]))

141
550


In [8]:
from keras.utils.data_utils import pad_sequences
#length is not same hence need to add padding
X_train= pad_sequences(X_train,padding='post',maxlen=50)

X_test= pad_sequences(X_test,padding='post',maxlen=50)

In [9]:
X_train.shape

(25000, 50)

In [10]:
X_test.shape

(25000, 50)

In [11]:
model=Sequential()
#inside 1 Rnn cell i want 32 nodes
model.add(SimpleRNN(32,input_shape=(50,1),return_sequences=False))
model.add(Dense(1,activation='sigmoid'))

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn (SimpleRNN)      (None, 32)                1088      
                                                                 
 dense (Dense)               (None, 1)                 33        
                                                                 
Total params: 1,121
Trainable params: 1,121
Non-trainable params: 0
_________________________________________________________________


In [12]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

model.fit(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

Epoch 1/5
782/782 [==============================] - 15s 16ms/step - loss: 0.6978 - accuracy: 0.5070 - val_loss: 0.6942 - val_accuracy: 0.5007
Epoch 2/5
782/782 [==============================] - 12s 16ms/step - loss: 0.6932 - accuracy: 0.5049 - val_loss: 0.6944 - val_accuracy: 0.5032
Epoch 3/5
782/782 [==============================] - 10s 13ms/step - loss: 0.6931 - accuracy: 0.5066 - val_loss: 0.6937 - val_accuracy: 0.5064
Epoch 4/5
782/782 [==============================] - 10s 13ms/step - loss: 0.6930 - accuracy: 0.5082 - val_loss: 0.6936 - val_accuracy: 0.5051
Epoch 5/5
782/782 [==============================] - 11s 14ms/step - loss: 0.6928 - accuracy: 0.5056 - val_loss: 0.6930 - val_accuracy: 0.5064


In [13]:
X_test[0].shape

(50,)

In [16]:
pred_test=X_test[0].reshape(1,-1)

#Prediction

In [18]:
model.predict(pred_test)

1/1 [==============================] - 0s 25ms/step


array([[0.4936445]], dtype=float32)

# Encoding using keras embeddings

In [1]:
docs = ['recurrent neural network',
		'neural network',
		'artificial neural',
		'connections between nodes',
		'can create a cycle',
		'allowing output',
		'some nodes to affect subsequent',
		'exhibit temporal',
		'dynamic behavior',
		'type of Neural Network',
    'affect subsequent']

In [2]:
from keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()

In [3]:
tokenizer.fit_on_texts(docs)

In [4]:
len(tokenizer.word_index)

23

In [5]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[6, 1, 2],
 [1, 2],
 [7, 1],
 [8, 9, 3],
 [10, 11, 12, 13],
 [14, 15],
 [16, 3, 17, 4, 5],
 [18, 19],
 [20, 21],
 [22, 23, 1, 2],
 [4, 5]]

In [6]:
from keras.utils import pad_sequences
sequences = pad_sequences(sequences,padding='post')
sequences

array([[ 6,  1,  2,  0,  0],
       [ 1,  2,  0,  0,  0],
       [ 7,  1,  0,  0,  0],
       [ 8,  9,  3,  0,  0],
       [10, 11, 12, 13,  0],
       [14, 15,  0,  0,  0],
       [16,  3, 17,  4,  5],
       [18, 19,  0,  0,  0],
       [20, 21,  0,  0,  0],
       [22, 23,  1,  2,  0],
       [ 4,  5,  0,  0,  0]], dtype=int32)

In [7]:
from keras.layers import Embedding

In [10]:
model = Sequential()
model.add(Embedding(23,output_dim=2,input_length=5))

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 5, 2)              46        
                                                                 
Total params: 46
Trainable params: 46
Non-trainable params: 0
_________________________________________________________________


In [11]:
model.compile('adam','accuracy')

In [12]:
pred = model.predict(sequences)
print(pred)

1/1 [==============================] - 0s 108ms/step
[[[ 0.02965966 -0.03247031]
  [ 0.0085485  -0.02891114]
  [-0.00476535  0.03303419]
  [-0.02735313 -0.00881309]
  [-0.02735313 -0.00881309]]

 [[ 0.0085485  -0.02891114]
  [-0.00476535  0.03303419]
  [-0.02735313 -0.00881309]
  [-0.02735313 -0.00881309]
  [-0.02735313 -0.00881309]]

 [[ 0.01400239  0.04195103]
  [ 0.0085485  -0.02891114]
  [-0.02735313 -0.00881309]
  [-0.02735313 -0.00881309]
  [-0.02735313 -0.00881309]]

 [[-0.04828208  0.01685948]
  [-0.04966983 -0.02635912]
  [ 0.04014215  0.02660492]
  [-0.02735313 -0.00881309]
  [-0.02735313 -0.00881309]]

 [[ 0.01958286 -0.01704063]
  [-0.00102644 -0.0445752 ]
  [-0.04992523  0.02076656]
  [ 0.0252995  -0.00857317]
  [-0.02735313 -0.00881309]]

 [[-0.01770631 -0.03028019]
  [-0.01799406 -0.01540803]
  [-0.02735313 -0.00881309]
  [-0.02735313 -0.00881309]
  [-0.02735313 -0.00881309]]

 [[ 0.04735127 -0.00307015]
  [ 0.04014215  0.02660492]
  [-0.04837661 -0.01930141]
  [ 0.01636

# Sentiment Analysis using Embedding layer

In [13]:
from keras.datasets import imdb
from keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [14]:
(X_train,y_train),(X_test,y_test) = imdb.load_data()

17464789/17464789 [==============================] - 2s 0us/step


In [15]:
X_train = pad_sequences(X_train,padding='post',maxlen=50)
X_test = pad_sequences(X_test,padding='post',maxlen=50)

In [16]:
X_train.shape

(25000, 50)

In [17]:
model = Sequential()
model.add(Embedding(10000,output_dim=2,input_length=50))
model.add(SimpleRNN(32,return_sequences=False))
model.add(Dense(1, activation='sigmoid'))

model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 50, 2)             20000     
                                                                 
 simple_rnn (SimpleRNN)      (None, 32)                1120      
                                                                 
 dense (Dense)               (None, 1)                 33        
                                                                 
Total params: 21,153
Trainable params: 21,153
Non-trainable params: 0
_________________________________________________________________


In [18]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
history = model.fit(X_train, y_train,epochs=5,validation_data=(X_test,y_test))

Epoch 1/5
782/782 [==============================] - 79s 93ms/step - loss: 0.5640 - acc: 0.6847 - val_loss: 0.4290 - val_acc: 0.8045
Epoch 2/5
782/782 [==============================] - 51s 66ms/step - loss: 0.3730 - acc: 0.8391 - val_loss: 0.4307 - val_acc: 0.8104
Epoch 3/5
782/782 [==============================] - 51s 65ms/step - loss: 0.3170 - acc: 0.8684 - val_loss: 0.4304 - val_acc: 0.8065
Epoch 4/5
782/782 [==============================] - 49s 63ms/step - loss: 0.2815 - acc: 0.8906 - val_loss: 0.4613 - val_acc: 0.8024
Epoch 5/5
782/782 [==============================] - 50s 64ms/step - loss: 0.2572 - acc: 0.9002 - val_loss: 0.5017 - val_acc: 0.7965


In [19]:
test_data = X_test[0][0:50].reshape(1,-1)
model.predict(test_data)

1/1 [==============================] - 0s 258ms/step


array([[0.32956582]], dtype=float32)