Some common terms to remember:
1. Corpus
2. Vocabulary
3. Document
4. Word

# Bag of words

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({"text":["people watch somesh",
                         "somesh watch somesh",
                         "people write comment",
                          "somesh write comment"],"output":[1,1,0,0]})

df

text  output
0   people watch somesh       1
1   somesh watch somesh       1
2  people write comment       0
3  somesh write comment       0

In [3]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [4]:
bow = cv.fit_transform(df['text'])

In [5]:
#vocabulary
print(cv.vocabulary_)

{'people': 1, 'watch': 3, 'somesh': 2, 'write': 4, 'comment': 0}


In [6]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[0 1 1 1 0]]
[[0 2 0 1 0]]
[[1 0 1 0 1]]


In [6]:
# new
cv.transform(['Somesh watch Trivedi']).toarray()

array([[0, 0, 1, 1, 0]], dtype=int64)

#  N-grams

In [7]:
df = pd.DataFrame({"text":["people watch somesh",
                         "somesh watch somesh",
                         "people write comment",
                          "somesh write comment"],"output":[1,1,0,0]})


df

text  output
0   people watch somesh       1
1   somesh watch somesh       1
2  people write comment       0
3  somesh write comment       0

In [8]:
# BI grams
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(2,2))

In [9]:
bow = cv.fit_transform(df['text'])

In [10]:
print(cv.vocabulary_)

{'people watch': 0, 'watch somesh': 4, 'somesh watch': 2, 'people write': 1, 'write comment': 5, 'somesh write': 3}


In [11]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[1 0 0 0 1 0]]
[[0 0 1 0 1 0]]
[[0 1 0 0 0 1]]


# TF-IDF (Term frequency- Inverse document frequency)

In [12]:
df = pd.DataFrame({"text":["people watch somesh",
                         "somesh watch somesh",
                         "people write comment",
                          "somesh write comment"],"output":[1,1,0,0]})

df

text  output
0   people watch somesh       1
1   somesh watch somesh       1
2  people write comment       0
3  somesh write comment       0

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfid= TfidfVectorizer()

In [14]:
tfid.fit_transform(df['text']).toarray()

array([[0.        , 0.61366674, 0.49681612, 0.61366674, 0.        ],
       [0.        , 0.        , 0.8508161 , 0.52546357, 0.        ],
       [0.57735027, 0.57735027, 0.        , 0.        , 0.57735027],
       [0.61366674, 0.        , 0.49681612, 0.        , 0.61366674]])

In [15]:
print(tfid.idf_)

[1.51082562 1.51082562 1.22314355 1.51082562 1.51082562]


In [17]:
print(tfid.get_feature_names_out())

['comment' 'people' 'somesh' 'watch' 'write']
